### PR TITLE
Tags feature

### PR DESCRIPTION
**Pull request by robertrosman**
Been working on implementing tags to be able to categorize the records (especially favorites). Basically you can add and remove tags by clicking the tag icon beside the star. Tags will be unique per record and multiple tags can be inserted at once if comma separated. Hit enter or the plus icon to add.

When searching for records, you can now use `t:xxx,yyy` to only show records with the tags xxx _and_ yyy (also matching substrings, so a tag like abcxxxdef would also show up).

In the database, tags are stored in a new column and separated by comma. Not the most beautiful solution, but works just fine. Storing them in a separate `tag` table (and maybe even joined with a junction table like record_tag) would probably be considered best practice, but also introduce some unneccessary complexity.

I also fiddled around with highlighting matched tags when searching, but it wasn't giving that much. They're short enough and you know what you search for, so it feels a little overkill.

I think it's good enough to fit my needs, please let me know what you think.

demo6
demo7

### CODE REVIEW

**Comment by robertrosman** [comment]
Forgot to mention, I only added translation for english since I don't know any Chinese.

**Comment by ChurchTao** [comment]
Thank you so much, I am not at home today, I will take a look at this feature later, and then discuss with you how this feature can be better integrated.

**Comment by ChurchTao** [comment]
> Forgot to mention, I only added translation for english since I don't know any Chinese.

I'll do it.

**Comment by robertrosman** [comment]
> Thank you so much, I am not at home today, I will take a look at this feature later, and then discuss with you how this feature can be better integrated.

Sounds good, thanks!

**Comment by ChurchTao** [comment]
@robertrosman 
image
I adjusted the structure a little to make the new features better integrated.
In fact, one reason is that your version missed to consider that when copying large text, adding tags will cause overlap.

**Comment by robertrosman** [comment]
Cool, thanks @ChurchTao! One thing I noticed, is this commented line intentional or only for debugging purposes? https://github.com/ChurchTao/Lanaya/blob/master/src/views/Main.vue#L199

**Comment by ChurchTao** [comment]
> Cool, thanks @ChurchTao! One thing I noticed, is this commented line intentional or only for debugging purposes? https://github.com/ChurchTao/Lanaya/blob/master/src/views/Main.vue#L199

Oh I always forget this. Is only for debugging.

**Pull request merged**
